kind: pipeline
type: docker
name: default

steps:
- name: build
  image: maven:3-jdk-11
  commands:
  - mvn -Dmaven.test.skip=true assembly:assembly
- name: tests
  image: maven:3-jdk-11
  commands:
  - mvn test
- name: pmd
  image: rawdee/pmd
  commands:
  - pmd -d src/main/java -f text -R pmd_ruleset.xml -language java
- name: publish
  image: plugins/docker
  settings:
<<<<<<< HEAD
    repo: fleck010360/public_fleckess
=======
    repo: fleckess/public_fleckess
>>>>>>> 99633af2d43a2e480899f642787a893a44a7e4dc
    username:
      from_secret: dockerhub_user
    password:
      from_secret: dockerhub
